name: okul_com_tm
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter

  #Core
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1
  flutter_riverpod: ^2.6.1
  kartal: ^4.1.0
  change_app_package_name: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0  
  flutter_lints: ^4.0.0
  
flutter:
  uses-material-design: true
